# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Movie.create([
  { cast_members_id: [],
    categories_id: [],
    directors_id: [],
    production_company_id: [],
    writers_id: [],
    awards: [],
    budget: 20000000,
    country: 'USA',
    filming_locations: 'Hollywood, Ca',
    gross: 100000000,
    language: 'English',
    motion_picture_rated: 'R',
    official_site: 'http://www.themovie.com',
    photos: [],
    rating: 8.1,
    release_date: Time.now - 10.years,
    runtime: 2.hours,
    storyline: 'A movie about things.',
    title: 'The Movie part 1',
    videos: [],
    vote_count: 1403,
  },
  { cast_members_id: [],
    categories_id: [],
    directors_id: [],
    production_company_id: [],
    writers_id: [],
    awards: [],
    budget: 10000000,
    country: 'USA',
    filming_locations: 'Hollywood, Ca',
    gross: 50000000,
    language: 'English',
    motion_picture_rated: 'R',
    official_site: 'http://www.themovie.com',
    photos: [],
    rating: 7.8,
    release_date: Time.now - 10.years,
    runtime: 2.hours,
    storyline: 'A movie about things.',
    title: 'The Movie part 2',
    videos: [],
    vote_count: 1403,
  },
  { cast_members_id: [],
    categories_id: [],
    directors_id: [],
    production_company_id: [],
    writers_id: [],
    awards: [],
    budget: 10000000,
    country: 'USA',
    filming_locations: 'Hollywood, Ca',
    gross: 50000000,
    language: 'English',
    motion_picture_rated: 'R',
    official_site: 'http://www.themovie.com',
    photos: [],
    rating: 5.6,
    release_date: Time.now - 10.years,
    runtime: 2.hours,
    storyline: 'A movie about things.',
    title: 'The Movie part 3',
    videos: [],
    vote_count: 1403,
  },
  { cast_members_id: [],
    categories_id: [],
    directors_id: [],
    production_company_id: [],
    writers_id: [],
    awards: [],
    budget: 10000000,
    country: 'USA',
    filming_locations: 'Hollywood, Ca',
    gross: 50000000,
    language: 'English',
    motion_picture_rated: 'R',
    official_site: 'http://www.themovie.com',
    photos: [],
    rating: 3.4,
    release_date: Time.now - 10.years,
    runtime: 2.hours,
    storyline: 'A movie about things.',
    title: 'The Movie part 4',
    videos: [],
    vote_count: 1403,
  }
])
